update-binary: Refactor and enhance for compatibility
- Remove device and RAM type checks
- Make modem flashing mandatory
- Update necessary partitions and removed non-existent ones
- Add new instructions and comments for clarity

Signed-off-by: Spike <90617898+spike0en@users.noreply.github.com>

diff --git a/update-binary b/update-binary
--- a/update-binary
+++ b/update-binary
@@ -22,10 +22,10 @@ chooseport() {
   fi
 }
 
-# detect Magisk Manager/booted flashing
+# Detect Magisk Manager/booted flashing
 ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false
 $BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true
-$BOOTMODE && abort "You need to flash this Firmware from recovery!"
+$BOOTMODE && abort "You need to flash this from Orangefox Recovery!"
 
 ui_print "***************************************"
 ui_print "*  Nothing Phone (2) Firmware Flasher *"
@@ -40,39 +40,6 @@ mkdir -p $tmp
 unzip -o "$ZIPFILE" -d $tmp || abort "Failed to extract zip!"
 sleep 1
 
-# Device check
-supported=false
-ui_print "Checking device compatibility..."
-for i in 19805 20809; do
- for prop in "ro.boot.prjname" "ro.boot.project_name"; do
-    if [ "$(getprop $prop)" == "$i" ]; then
-      ui_print "- Supported Device detected"
-      supported=true
-      break 2
-    fi
-  done
-done
-$supported || abort "- Unsupported device! Aborting!"
-
-ddr4=false
-ddr5=false
-ui_print "Checking RAM type..."
-if [ "$(cat /proc/devinfo/ddr_type | grep -i DDR4)" ]; then
-  ddr4=true
-  ui_print "- DDR4 RAM detected!"
-elif [ "$(cat /proc/devinfo/ddr_type | grep -i DDR5)" ]; then
-  ddr5=true
-  ui_print "- DDR5 RAM detected!"
-elif [ "$(getprop ro.boot.ddr_type | grep -i 0)" ]; then
-  ddr4=true
-  ui_print "- DDR4 RAM detected!"
-elif [ "$(getprop ro.boot.ddr_type | grep -i 1)" ]; then
-  ddr5=true
-  ui_print "- DDR5 RAM detected!"
-else  ui_print "- Could not detect RAM type. Flashing aborted!" 
-  exit 0
-fi
-
 ui_print " "
 ui_print "**********************************************"
 ui_print "Device: Nothing Phone 2 (Pong)"
@@ -80,89 +47,103 @@ ui_print "Target NOS Build: <Mentioned in filename>"
 ui_print "**********************************************"
 ui_print " "
 ui_print "Continue? Vol+ yes, Vol- no"
-chooseport && flash=true|| exit 0
-ui_print "Flashing OOS13 F15 Firmware to both slots A and B..."
-ui_print " "
-modem=false
-ui_print "Do you want to update Modem.img? Vol+ yes, Vol- no"
-chooseport && modem=true || modem=false
-if [ "$modem" = "true" ]; then
- ui_print "Updating modem..."
-#dd if=/dev/tmp/firmware-update/modem.img of=/dev/block/bootdevice/by-name/modem_a bs=4k
-#dd if=/dev/tmp/firmware-update/modem.img of=/dev/block/bootdevice/by-name/modem_b bs=4k
-fi
+chooseport && flash=true || exit 0
+
+# Firmware partition images
+ui_print "Flashing Nothing OS firmware to both slots A and B..."
 ui_print "Updating abl..."
-#dd if=/dev/tmp/firmware-update/abl.img of=/dev/block/bootdevice/by-name/abl_a bs=4k
-#dd if=/dev/tmp/firmware-update/abl.img of=/dev/block/bootdevice/by-name/abl_b bs=4k
+dd if=/dev/tmp/firmware-update/abl.img of=/dev/block/bootdevice/by-name/abl_a bs=4k
+dd if=/dev/tmp/firmware-update/abl.img of=/dev/block/bootdevice/by-name/abl_b bs=4k
 ui_print "Updating aop..."
-#dd if=/dev/tmp/firmware-update/aop.img of=/dev/block/bootdevice/by-name/aop_a bs=4k
-#dd if=/dev/tmp/firmware-update/aop.img of=/dev/block/bootdevice/by-name/aop_b bs=4k
+dd if=/dev/tmp/firmware-update/aop.img of=/dev/block/bootdevice/by-name/aop_a bs=4k
+dd if=/dev/tmp/firmware-update/aop.img of=/dev/block/bootdevice/by-name/aop_b bs=4k
+ui_print "Updating aop_config..."
+dd if=/dev/tmp/firmware-update/aop_config.img of=/dev/block/bootdevice/by-name/aop_config_a bs=4k
+dd if=/dev/tmp/firmware-update/aop_config.img of=/dev/block/bootdevice/by-name/aop_config_b bs=4k
 ui_print "Updating bluetooth..."
-#dd if=/dev/tmp/firmware-update/bluetooth.img of=/dev/block/bootdevice/by-name/bluetooth_a bs=4k
-#dd if=/dev/tmp/firmware-update/bluetooth.img of=/dev/block/bootdevice/by-name/bluetooth_b bs=4k
-ui_print "Updating cmnlib..."
-#dd if=/dev/tmp/firmware-update/cmnlib.img of=/dev/block/bootdevice/by-name/cmnlib_a bs=4k
-#dd if=/dev/tmp/firmware-update/cmnlib.img of=/dev/block/bootdevice/by-name/cmnlib_b bs=4k
-ui_print "Updating cmnlib64..."
-#dd if=/dev/tmp/firmware-update/cmnlib64.img of=/dev/block/bootdevice/by-name/cmnlib64_a bs=4k
-#dd if=/dev/tmp/firmware-update/cmnlib64.img of=/dev/block/bootdevice/by-name/cmnlib64_b bs=4k
+dd if=/dev/tmp/firmware-update/bluetooth.img of=/dev/block/bootdevice/by-name/bluetooth_a bs=4k
+dd if=/dev/tmp/firmware-update/bluetooth.img of=/dev/block/bootdevice/by-name/bluetooth_b bs=4k
+ui_print "Updating cpucp..."
+dd if=/dev/tmp/firmware-update/cpucp.img of=/dev/block/bootdevice/by-name/cpucp_a bs=4k
+dd if=/dev/tmp/firmware-update/cpucp.img of=/dev/block/bootdevice/by-name/cpucp_b bs=4k
 ui_print "Updating devcfg..."
-#dd if=/dev/tmp/firmware-update/devcfg.img of=/dev/block/bootdevice/by-name/devcfg_a bs=4k
-#dd if=/dev/tmp/firmware-update/devcfg.img of=/dev/block/bootdevice/by-name/devcfg_b bs=4k
+dd if=/dev/tmp/firmware-update/devcfg.img of=/dev/block/bootdevice/by-name/devcfg_a bs=4k
+dd if=/dev/tmp/firmware-update/devcfg.img of=/dev/block/bootdevice/by-name/devcfg_b bs=4k
 ui_print "Updating dsp..."
-#dd if=/dev/tmp/firmware-update/dsp.img of=/dev/block/bootdevice/by-name/dsp_a bs=4k
-#dd if=/dev/tmp/firmware-update/dsp.img of=/dev/block/bootdevice/by-name/dsp_b bs=4k
+dd if=/dev/tmp/firmware-update/dsp.img of=/dev/block/bootdevice/by-name/dsp_a bs=4k
+dd if=/dev/tmp/firmware-update/dsp.img of=/dev/block/bootdevice/by-name/dsp_b bs=4k
 ui_print "Updating featenabler..."
-#dd if=/dev/tmp/firmware-update/featenabler.img of=/dev/block/bootdevice/by-name/featenabler_a bs=4k
-#dd if=/dev/tmp/firmware-update/featenabler.img of=/dev/block/bootdevice/by-name/featenabler_b bs=4k
+dd if=/dev/tmp/firmware-update/featenabler.img of=/dev/block/bootdevice/by-name/featenabler_a bs=4k
+dd if=/dev/tmp/firmware-update/featenabler.img of=/dev/block/bootdevice/by-name/featenabler_b bs=4k
 ui_print "Updating hyp..."
-#dd if=/dev/tmp/firmware-update/hyp.img of=/dev/block/bootdevice/by-name/hyp_a bs=4k
-#dd if=/dev/tmp/firmware-update/hyp.img of=/dev/block/bootdevice/by-name/hyp_b bs=4k
+dd if=/dev/tmp/firmware-update/hyp.img of=/dev/block/bootdevice/by-name/hyp_a bs=4k
+dd if=/dev/tmp/firmware-update/hyp.img of=/dev/block/bootdevice/by-name/hyp_b bs=4k
 ui_print "Updating imagefv..."
-#dd if=/dev/tmp/firmware-update/imagefv.img of=/dev/block/bootdevice/by-name/imagefv_a bs=4k
-#dd if=/dev/tmp/firmware-update/imagefv.img of=/dev/block/bootdevice/by-name/imagefv_b bs=4k
+dd if=/dev/tmp/firmware-update/imagefv.img of=/dev/block/bootdevice/by-name/imagefv_a bs=4k
+dd if=/dev/tmp/firmware-update/imagefv.img of=/dev/block/bootdevice/by-name/imagefv_b bs=4k
 ui_print "Updating keymaster..."
-#dd if=/dev/tmp/firmware-update/keymaster.img of=/dev/block/bootdevice/by-name/keymaster_a bs=4k
-#dd if=/dev/tmp/firmware-update/keymaster.img of=/dev/block/bootdevice/by-name/keymaster_b bs=4k
-ui_print "Updating logo..."
-#dd if=/dev/tmp/firmware-update/logo.img of=/dev/block/bootdevice/by-name/logo_a bs=4k
-#dd if=/dev/tmp/firmware-update/logo.img of=/dev/block/bootdevice/by-name/logo_b bs=4k
-ui_print "Updating mdm_oem_stanvbk..."
-#dd if=/dev/tmp/firmware-update/mdm_oem_stanvbk.img of=/dev/block/bootdevice/by-name/mdm_oem_stanvbk bs=4k
+dd if=/dev/tmp/firmware-update/keymaster.img of=/dev/block/bootdevice/by-name/keymaster_a bs=4k
+dd if=/dev/tmp/firmware-update/keymaster.img of=/dev/block/bootdevice/by-name/keymaster_b bs=4k
+ui_print "Updating modem..."
+dd if=/dev/tmp/firmware-update/modem.img of=/dev/block/bootdevice/by-name/modem_a bs=4k
+dd if=/dev/tmp/firmware-update/modem.img of=/dev/block/bootdevice/by-name/modem_b bs=4k
 ui_print "Updating multiimgoem..."
-#dd if=/dev/tmp/firmware-update/multiimgoem.img of=/dev/block/bootdevice/by-name/multiimgoem_a bs=4k
-#dd if=/dev/tmp/firmware-update/multiimgoem.img of=/dev/block/bootdevice/by-name/multiimgoem_b bs=4k
+dd if=/dev/tmp/firmware-update/multiimgoem.img of=/dev/block/bootdevice/by-name/multiimgoem_a bs=4k
+dd if=/dev/tmp/firmware-update/multiimgoem.img of=/dev/block/bootdevice/by-name/multiimgoem_b bs=4k
+ui_print "Updating multiimgqti..."
+dd if=/dev/tmp/firmware-update/multiimgqti.img of=/dev/block/bootdevice/by-name/multiimgqti_a bs=4k
+dd if=/dev/tmp/firmware-update/multiimgqti.img of=/dev/block/bootdevice/by-name/multiimgqti_b bs=4k
 ui_print "Updating qupfw..."
-#dd if=/dev/tmp/firmware-update/qupfw.img of=/dev/block/bootdevice/by-name/qupfw_a bs=4k
-#dd if=/dev/tmp/firmware-update/qupfw.img of=/dev/block/bootdevice/by-name/qupfw_b bs=4k
-ui_print "Updating spunvm..."
-#dd if=/dev/tmp/firmware-update/spunvm.img of=/dev/block/bootdevice/by-name/spunvm bs=4k
-ui_print "Updating storsec..."
-#dd if=/dev/tmp/firmware-update/storsec.img of=/dev/block/bootdevice/by-name/storsec_a bs=4k 
-#dd if=/dev/tmp/firmware-update/storsec.img of=/dev/block/bootdevice/by-name/storsec_b bs=4k
+dd if=/dev/tmp/firmware-update/qupfw.img of=/dev/block/bootdevice/by-name/qupfw_a bs=4k
+dd if=/dev/tmp/firmware-update/qupfw.img of=/dev/block/bootdevice/by-name/qupfw_b bs=4k
+ui_print "Updating qweslicstore..."
+dd if=/dev/tmp/firmware-update/qweslicstore.img of=/dev/block/bootdevice/by-name/qweslicstore_a bs=4k
+dd if=/dev/tmp/firmware-update/qweslicstore.img of=/dev/block/bootdevice/by-name/qweslicstore_b bs=4k
+ui_print "Updating shrm..."
+dd if=/dev/tmp/firmware-update/shrm.img of=/dev/block/bootdevice/by-name/shrm_a bs=4k
+dd if=/dev/tmp/firmware-update/shrm.img of=/dev/block/bootdevice/by-name/shrm_b bs=4k
 ui_print "Updating tz..."
-#dd if=/dev/tmp/firmware-update/tz.img of=/dev/block/bootdevice/by-name/tz_a bs=4k
-#dd if=/dev/tmp/firmware-update/tz.img of=/dev/block/bootdevice/by-name/tz_b bs=4k
+dd if=/dev/tmp/firmware-update/tz.img of=/dev/block/bootdevice/by-name/tz_a bs=4k
+dd if=/dev/tmp/firmware-update/tz.img of=/dev/block/bootdevice/by-name/tz_b bs=4k
+ui_print "Updating uefi..."
+dd if=/dev/tmp/firmware-update/uefi.img of=/dev/block/bootdevice/by-name/uefi_a bs=4k
+dd if=/dev/tmp/firmware-update/uefi.img of=/dev/block/bootdevice/by-name/uefi_b bs=4k
 ui_print "Updating uefisecapp..."
-#dd if=/dev/tmp/firmware-update/uefisecapp.img of=/dev/block/bootdevice/by-name/uefisecapp_a bs=4k
-#dd if=/dev/tmp/firmware-update/uefisecapp.img of=/dev/block/bootdevice/by-name/uefisecapp_b bs=4k
-if [ "$ddr4" = "true" ]; then
-   ui_print "Updating xbl for DDR4 RAM..."
-   #dd if=/dev/tmp/firmware-update/xbl.img of=/dev/block/bootdevice/by-name/xbl_a bs=4k
-   #dd if=/dev/tmp/firmware-update/xbl.img of=/dev/block/bootdevice/by-name/xbl_b bs=4k
-   ui_print "Updating xbl_config for DDR4 RAM..."
-   #dd if=/dev/tmp/firmware-update/xbl_config.img of=/dev/block/bootdevice/by-name/xbl_config_a bs=4k
-   #dd if=/dev/tmp/firmware-update/xbl_config.img of=/dev/block/bootdevice/by-name/xbl_config_b bs=4k 
-elif  [ "$ddr5" = "true" ]; then
-   ui_print "Updating xbl for DDR5 RAM..."
-   #dd if=/dev/tmp/firmware-update/xbl_lp5.img of=/dev/block/bootdevice/by-name/xbl_a bs=4k
-   #dd if=/dev/tmp/firmware-update/xbl_lp5.img of=/dev/block/bootdevice/by-name/xbl_b bs=4k
-   ui_print "Updating xbl_config for DDR5 RAM..."
-   #dd if=/dev/tmp/firmware-update/xbl_config_lp5.img of=/dev/block/bootdevice/by-name/xbl_config_a bs=4k
-   #dd if=/dev/tmp/firmware-update/xbl_config_lp5.img of=/dev/block/bootdevice/by-name/xbl_config_b bs=4k
-fi
+dd if=/dev/tmp/firmware-update/uefisecapp.img of=/dev/block/bootdevice/by-name/uefisecapp_a bs=4k
+dd if=/dev/tmp/firmware-update/uefisecapp.img of=/dev/block/bootdevice/by-name/uefisecapp_b bs=4k
+ui_print "Updating xbl..."
+dd if=/dev/tmp/firmware-update/xbl.img of=/dev/block/bootdevice/by-name/xbl_a bs=4k
+dd if=/dev/tmp/firmware-update/xbl.img of=/dev/block/bootdevice/by-name/xbl_b bs=4k
+ui_print "Updating xbl_config..."
+dd if=/dev/tmp/firmware-update/xbl_config.img of=/dev/block/bootdevice/by-name/xbl_config_a bs=4k
+dd if=/dev/tmp/firmware-update/xbl_config.img of=/dev/block/bootdevice/by-name/xbl_config_b bs=4k
+ui_print "Firmware flashing complete!"
+
+# Misc partition images
+ui_print "Flashing some additionally required partition images to both slots A and B..."
+ui_print "Updating boot..."
+dd if=/dev/tmp/firmware-update/boot.img of=/dev/block/bootdevice/by-name/boot_a bs=4k
+dd if=/dev/tmp/firmware-update/boot.img of=/dev/block/bootdevice/by-name/boot_b bs=4k
+ui_print "Updating dtbo..."
+dd if=/dev/tmp/firmware-update/dtbo.img of=/dev/block/bootdevice/by-name/dtbo_a bs=4k
+dd if=/dev/tmp/firmware-update/dtbo.img of=/dev/block/bootdevice/by-name/dtbo_b bs=4k
+ui_print "Updating vendor_boot..."
+dd if=/dev/tmp/firmware-update/vendor_boot.img of=/dev/block/bootdevice/by-name/vendor_boot_a bs=4k
+dd if=/dev/tmp/firmware-update/vendor_boot.img of=/dev/block/bootdevice/by-name/vendor_boot_b bs=4k
+ui_print "Updating vbmeta_vendor..."
+dd if=/dev/tmp/firmware-update/vbmeta_vendor.img of=/dev/block/bootdevice/by-name/vbmeta_vendor_a bs=4k
+dd if=/dev/tmp/firmware-update/vbmeta_vendor.img of=/dev/block/bootdevice/by-name/vbmeta_vendor_b bs=4k
+ui_print "Updating vbmeta_system..."
+dd if=/dev/tmp/firmware-update/vbmeta_system.img of=/dev/block/bootdevice/by-name/vbmeta_system_a bs=4k
+dd if=/dev/tmp/firmware-update/vbmeta_system.img of=/dev/block/bootdevice/by-name/vbmeta_system_b bs=4k
+ui_print "Flashing has been completed!"
+
+# Cleanup tmp dir
 rm -rf /dev/tmp
+
+# Final instruction
 ui_print " "
-ui_print "Firmware flashing completed!"
+ui_print "If you want to flash a new ROM do that now before rebooting."
+ui_print "NothingMuchROM users may also flash super and vbmeta (optional)."
 
 exit 0
