update-binary: Introduce `flash_partition` function with error handling
- Flash the image to both slots A and B using `dd`.
- Check if the source image file exists within the extracted zip before attempting to flash.
- Check the exit status of each `dd` command.
- Abort the script immediately via the `abort` function if the image file is missing or if any `dd` operation fails, providing a specific error message to the user.

Signed-off-by: Spike <90617898+spike0en@users.noreply.github.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -49,94 +49,68 @@ ui_print " "
 ui_print "Continue? Vol+ yes, Vol- no"
 chooseport && flash=true || exit 0
 
+# Function to flash a partition to both slots with error checking
+flash_partition() {
+  local partition_name=$1
+  local image_file=$2
+  local partition_path_a="/dev/block/bootdevice/by-name/${partition_name}_a"
+  local partition_path_b="/dev/block/bootdevice/by-name/${partition_name}_b"
+  local source_image="$tmp/firmware-update/$image_file"
+
+  ui_print "Updating $partition_name..."
+
+  # Check if image file exists
+  if [ ! -f "$source_image" ]; then
+    abort "Error: Image file $source_image not found in zip!"
+  fi
+
+  # Flash Slot A
+  dd if="$source_image" of="$partition_path_a" bs=4k
+  if [ $? -ne 0 ]; then
+    abort "Error flashing $partition_name to slot A!"
+  fi
+
+  # Flash Slot B
+  dd if="$source_image" of="$partition_path_b" bs=4k
+  if [ $? -ne 0 ]; then
+    abort "Error flashing $partition_name to slot B!"
+  fi
+}
+
 # Firmware partition images
 ui_print "Flashing Nothing OS firmware to both slots A and B..."
-ui_print "Updating abl..."
-dd if=/dev/tmp/firmware-update/abl.img of=/dev/block/bootdevice/by-name/abl_a bs=4k
-dd if=/dev/tmp/firmware-update/abl.img of=/dev/block/bootdevice/by-name/abl_b bs=4k
-ui_print "Updating aop..."
-dd if=/dev/tmp/firmware-update/aop.img of=/dev/block/bootdevice/by-name/aop_a bs=4k
-dd if=/dev/tmp/firmware-update/aop.img of=/dev/block/bootdevice/by-name/aop_b bs=4k
-ui_print "Updating aop_config..."
-dd if=/dev/tmp/firmware-update/aop_config.img of=/dev/block/bootdevice/by-name/aop_config_a bs=4k
-dd if=/dev/tmp/firmware-update/aop_config.img of=/dev/block/bootdevice/by-name/aop_config_b bs=4k
-ui_print "Updating bluetooth..."
-dd if=/dev/tmp/firmware-update/bluetooth.img of=/dev/block/bootdevice/by-name/bluetooth_a bs=4k
-dd if=/dev/tmp/firmware-update/bluetooth.img of=/dev/block/bootdevice/by-name/bluetooth_b bs=4k
-ui_print "Updating cpucp..."
-dd if=/dev/tmp/firmware-update/cpucp.img of=/dev/block/bootdevice/by-name/cpucp_a bs=4k
-dd if=/dev/tmp/firmware-update/cpucp.img of=/dev/block/bootdevice/by-name/cpucp_b bs=4k
-ui_print "Updating devcfg..."
-dd if=/dev/tmp/firmware-update/devcfg.img of=/dev/block/bootdevice/by-name/devcfg_a bs=4k
-dd if=/dev/tmp/firmware-update/devcfg.img of=/dev/block/bootdevice/by-name/devcfg_b bs=4k
-ui_print "Updating dsp..."
-dd if=/dev/tmp/firmware-update/dsp.img of=/dev/block/bootdevice/by-name/dsp_a bs=4k
-dd if=/dev/tmp/firmware-update/dsp.img of=/dev/block/bootdevice/by-name/dsp_b bs=4k
-ui_print "Updating featenabler..."
-dd if=/dev/tmp/firmware-update/featenabler.img of=/dev/block/bootdevice/by-name/featenabler_a bs=4k
-dd if=/dev/tmp/firmware-update/featenabler.img of=/dev/block/bootdevice/by-name/featenabler_b bs=4k
-ui_print "Updating hyp..."
-dd if=/dev/tmp/firmware-update/hyp.img of=/dev/block/bootdevice/by-name/hyp_a bs=4k
-dd if=/dev/tmp/firmware-update/hyp.img of=/dev/block/bootdevice/by-name/hyp_b bs=4k
-ui_print "Updating imagefv..."
-dd if=/dev/tmp/firmware-update/imagefv.img of=/dev/block/bootdevice/by-name/imagefv_a bs=4k
-dd if=/dev/tmp/firmware-update/imagefv.img of=/dev/block/bootdevice/by-name/imagefv_b bs=4k
-ui_print "Updating keymaster..."
-dd if=/dev/tmp/firmware-update/keymaster.img of=/dev/block/bootdevice/by-name/keymaster_a bs=4k
-dd if=/dev/tmp/firmware-update/keymaster.img of=/dev/block/bootdevice/by-name/keymaster_b bs=4k
-ui_print "Updating modem..."
-dd if=/dev/tmp/firmware-update/modem.img of=/dev/block/bootdevice/by-name/modem_a bs=4k
-dd if=/dev/tmp/firmware-update/modem.img of=/dev/block/bootdevice/by-name/modem_b bs=4k
-ui_print "Updating multiimgoem..."
-dd if=/dev/tmp/firmware-update/multiimgoem.img of=/dev/block/bootdevice/by-name/multiimgoem_a bs=4k
-dd if=/dev/tmp/firmware-update/multiimgoem.img of=/dev/block/bootdevice/by-name/multiimgoem_b bs=4k
-ui_print "Updating multiimgqti..."
-dd if=/dev/tmp/firmware-update/multiimgqti.img of=/dev/block/bootdevice/by-name/multiimgqti_a bs=4k
-dd if=/dev/tmp/firmware-update/multiimgqti.img of=/dev/block/bootdevice/by-name/multiimgqti_b bs=4k
-ui_print "Updating qupfw..."
-dd if=/dev/tmp/firmware-update/qupfw.img of=/dev/block/bootdevice/by-name/qupfw_a bs=4k
-dd if=/dev/tmp/firmware-update/qupfw.img of=/dev/block/bootdevice/by-name/qupfw_b bs=4k
-ui_print "Updating qweslicstore..."
-dd if=/dev/tmp/firmware-update/qweslicstore.img of=/dev/block/bootdevice/by-name/qweslicstore_a bs=4k
-dd if=/dev/tmp/firmware-update/qweslicstore.img of=/dev/block/bootdevice/by-name/qweslicstore_b bs=4k
-ui_print "Updating shrm..."
-dd if=/dev/tmp/firmware-update/shrm.img of=/dev/block/bootdevice/by-name/shrm_a bs=4k
-dd if=/dev/tmp/firmware-update/shrm.img of=/dev/block/bootdevice/by-name/shrm_b bs=4k
-ui_print "Updating tz..."
-dd if=/dev/tmp/firmware-update/tz.img of=/dev/block/bootdevice/by-name/tz_a bs=4k
-dd if=/dev/tmp/firmware-update/tz.img of=/dev/block/bootdevice/by-name/tz_b bs=4k
-ui_print "Updating uefi..."
-dd if=/dev/tmp/firmware-update/uefi.img of=/dev/block/bootdevice/by-name/uefi_a bs=4k
-dd if=/dev/tmp/firmware-update/uefi.img of=/dev/block/bootdevice/by-name/uefi_b bs=4k
-ui_print "Updating uefisecapp..."
-dd if=/dev/tmp/firmware-update/uefisecapp.img of=/dev/block/bootdevice/by-name/uefisecapp_a bs=4k
-dd if=/dev/tmp/firmware-update/uefisecapp.img of=/dev/block/bootdevice/by-name/uefisecapp_b bs=4k
-ui_print "Updating xbl..."
-dd if=/dev/tmp/firmware-update/xbl.img of=/dev/block/bootdevice/by-name/xbl_a bs=4k
-dd if=/dev/tmp/firmware-update/xbl.img of=/dev/block/bootdevice/by-name/xbl_b bs=4k
-ui_print "Updating xbl_config..."
-dd if=/dev/tmp/firmware-update/xbl_config.img of=/dev/block/bootdevice/by-name/xbl_config_a bs=4k
-dd if=/dev/tmp/firmware-update/xbl_config.img of=/dev/block/bootdevice/by-name/xbl_config_b bs=4k
+flash_partition abl abl.img
+flash_partition aop aop.img
+flash_partition aop_config aop_config.img
+flash_partition bluetooth bluetooth.img
+flash_partition cpucp cpucp.img
+flash_partition devcfg devcfg.img
+flash_partition dsp dsp.img
+flash_partition featenabler featenabler.img
+flash_partition hyp hyp.img
+flash_partition imagefv imagefv.img
+flash_partition keymaster keymaster.img
+flash_partition modem modem.img
+flash_partition multiimgoem multiimgoem.img
+flash_partition multiimgqti multiimgqti.img
+flash_partition qupfw qupfw.img
+flash_partition qweslicstore qweslicstore.img
+flash_partition shrm shrm.img
+flash_partition tz tz.img
+flash_partition uefi uefi.img
+flash_partition uefisecapp uefisecapp.img
+flash_partition xbl xbl.img
+flash_partition xbl_config xbl_config.img
 ui_print "Firmware flashing complete!"
 
 # Misc partition images
 ui_print "Flashing some additionally required partition images to both slots A and B..."
-ui_print "Updating boot..."
-dd if=/dev/tmp/firmware-update/boot.img of=/dev/block/bootdevice/by-name/boot_a bs=4k
-dd if=/dev/tmp/firmware-update/boot.img of=/dev/block/bootdevice/by-name/boot_b bs=4k
-ui_print "Updating dtbo..."
-dd if=/dev/tmp/firmware-update/dtbo.img of=/dev/block/bootdevice/by-name/dtbo_a bs=4k
-dd if=/dev/tmp/firmware-update/dtbo.img of=/dev/block/bootdevice/by-name/dtbo_b bs=4k
-ui_print "Updating vendor_boot..."
-dd if=/dev/tmp/firmware-update/vendor_boot.img of=/dev/block/bootdevice/by-name/vendor_boot_a bs=4k
-dd if=/dev/tmp/firmware-update/vendor_boot.img of=/dev/block/bootdevice/by-name/vendor_boot_b bs=4k
-ui_print "Updating vbmeta_vendor..."
-dd if=/dev/tmp/firmware-update/vbmeta_vendor.img of=/dev/block/bootdevice/by-name/vbmeta_vendor_a bs=4k
-dd if=/dev/tmp/firmware-update/vbmeta_vendor.img of=/dev/block/bootdevice/by-name/vbmeta_vendor_b bs=4k
-ui_print "Updating vbmeta_system..."
-dd if=/dev/tmp/firmware-update/vbmeta_system.img of=/dev/block/bootdevice/by-name/vbmeta_system_a bs=4k
-dd if=/dev/tmp/firmware-update/vbmeta_system.img of=/dev/block/bootdevice/by-name/vbmeta_system_b bs=4k
-ui_print "Flashing has been completed!"
+flash_partition boot boot.img
+flash_partition dtbo dtbo.img
+flash_partition vendor_boot vendor_boot.img
+flash_partition vbmeta_vendor vbmeta_vendor.img
+flash_partition vbmeta_system vbmeta_system.img
+ui_print "Additional partition flashing complete!"
 
 # Cleanup tmp dir
 rm -rf /dev/tmp
